#
# Makefile
#

CIRCLEHOME = ../..

OBJS	= main.o kernel.o

LIBS	= $(CIRCLEHOME)/app/lib/arduino/libarduino.a \
		$(CIRCLEHOME)/app/lib/SSD1306Ascii/libssd1306ascii.a \
	  $(CIRCLEHOME)/lib/libcircle.a

include ../Rules.mk
