#
# Makefile
#

CIRCLEHOME = ../..

OBJS	= main.o kernel.o

LIBS	= $(CIRCLEHOME)/app/lib/arduino/libarduino.a \
		$(CIRCLEHOME)/app/lib/u8g2/libu8g2.a \
	  $(CIRCLEHOME)/lib/libcircle.a

include ../Rules.mk
