#!/bin/bash

make="${MAKE:-gmake}"

pushd lib

pushd arduino
$make $1 $2 || exit
popd 

pushd SSD1306Ascii
$make $1 $2 || exit
popd 

popd

pushd template
$make $1 $2 || exit
popd

# TODO: Add new apps here
#cd subdir
#$make $1 $2 || exit
#cd ..

