#!/bin/bash

make="${MAKE:-gmake}"

pushd lib

pushd template
$make $1 $2 || exit
popd

pushd arduino
$make $1 $2 || exit
popd 

# TODO: Add new libs here
pushd u8g2
$make $1 $2 || exit
popd 

popd

pushd template
$make $1 $2 || exit
popd

# TODO: Add new apps here
#cd subdir
#$make $1 $2 || exit
#cd ..

